### PR TITLE
fix: export logic

### LINKED ISSUE #673: Wrong checkbox "Export all" logic
When exporting a list of documents (all sections except "Notes" can be exported) to Excel or CSV, the "number of records" checkbox in the pop-up window does not work. If you click it or do not click it, in both cases all documents are downloaded. 

What is the idea? Maybe should appear additional filter after checkbox "Export All" is empty?

### PR DESCRIPTION
**Pull request by pratikb64**
Fixed export logic where while exporting data when user selects rows from list view only those rows are exported instead of all

Fixes #673

### CODE REVIEW

**Comment by pratikb64** [comment]
@mergifyio refresh

File: frontend/src/components/ViewControls.vue [hunk 1]
```diff
@@ -560,7 +565,15 @@ async function exportRows() {
     page_length = list.value.data.total_count
   }
 
-  window.location.href = `/api/method/frappe.desk.reportview.export_query?file_format_type=${export_type.value}&title=${props.doctype}&doctype=${props.doctype}&fields=${fields}&filters=${filters}&order_by=${order_by}&page_length=${page_length}&start=0&view=Report&with_comment_count=1`
+  let url = `/api/method/frappe.desk.reportview.export_query?file_format_type=${export_type.value}&title=${props.doctype}&doctype=${props.doctype}&fields=${fields}&filters=${filters}&order_by=${order_by}&page_length=${page_length}&start=0&view=Report&with_comment_count=1`
+
+  // Add selected items parameter if rows are selected
+  if (selectedRows.value?.length && !export_all.value) {
+    url += `&selected_items=${JSON.stringify(selectedRows.value)}`
+  }
```
Comment (shariquerik) [inline frontend/src/components/ViewControls.vue:573]: This will not work since selectedRows is a Set

**Review by shariquerik — CHANGES_REQUESTED** [review]

File: frontend/src/components/ViewControls.vue (hunk 1 above)
Comment (pratikb64) [reply frontend/src/components/ViewControls.vue:573]: It works because at line 551 in updateSelections function it is getting converted to array
